### ISSUE TITLE
spacenavd-version to old for newes spnavcfg-version

### ISSUE THREAD

**Issue by Giant0** [FreeSpacenav/spnavcfg#16]
Hey, 
first of all I think it's realy cool that you are developing and prviding a driver for the 3Dconnexion mice.

I have noticed that the newest spacenavd version is v0.8 and the documentation of spnavcfg says that it needs at least v0.9. 
Is this intentional? Or am I missing something?

Thanks again!

**Comment by jtsiomb** [comment]
It's in preperation for the new release which will happen very soon. It will be a simultaneous release of spacenavd, libspnav and spnavcfg. And possibly it will be v1.0 not 0.9 as I initially implied, because there are lots of changes and improvements across all three. And those realy work hand in hand.

What it means at this point is that you basically need the current git HEAD spacenavd for the current git version of spnavcfg. And the current version of spnavcfg also depends on the current git version of libspnav.

It will be less confusing when all of them are just called v1.0
