### ISSUE TITLE
Add SpaceMouse Pro Wireless

### ISSUE THREAD

**Issue by Takrel** [FreeSpacenav/spnavcfg#45]
Hello

Is it possible to add in 1.4 the SpaceMouse Pro Wireless?

I can't use some of the buttons and receive always this message when i press them in spnavcfg.
This error will be appearing when i press ESC, SHIFT, CTRL, ALT & 4

Second isswue with the buttons. MENU doesn't work. Maybe because of same reasons.
![Error spnavcfg](https://github.com/user-attachments/assets/5db2b5fe-db02-4c5e-89ca-d3b23ed8fa29)
![20240712_114655_marked](https://github.com/user-attachments/assets/a6d48ea7-1202-4dee-a697-b65b5b783ba9)

Thank you for this great software and your time!

**Comment by jtsiomb** [comment]
Thanks for reporting it. Could you give me a few more pieces of information? Specifically:

  1. the USB vendor and device ID your device reports (see lsusb).
  2. post the spacenavd log file (default: /var/log/spnav.log ). If there is no log file, your init script might have instructed spacenavd to log to syslog or to a different file. In that case I think the simpler thing to do is to just stop the daemon and run it manually in a root terminal as: `spacenavd -d -v` then paste the output. Hit ctrl-c to stop it when you're done.
  3. With spacenavd running, please run spnavcfg and write down exactly which button number is reported when pressing every button on the device. To do that go to the "Buttons" tab, and check the "Buttons pressed:" line at the top while you're pressing buttons.

**Comment by Takrel** [comment]
Hello

Ok. I try to get you all what you want.

Log

**Comment by Takrel** [comment]
Hello

I try to get you all what you want.

Log: 
[spnavd.log](https://github.com/user-attachments/files/16192449/spnavd.log)

lsusb:
Bus 001 Device 003: ID 256f:c652 3Dconnexion Universal Receiver

The button numbers are: 15, 22, 23, 24, 25 & 26
The menu button does nothing. No error and no function.

**Comment by Takrel** [comment]
I addes now all button numbers to the picture.
Hopefully this helps you.

![20240712_114655_button numbers](https://github.com/user-attachments/assets/75222d7c-49ba-40bb-b873-e6ce2eeba958)

**Comment by jtsiomb** [comment]
Ok makes sense. As you can see the device is reported as "3Dconnexion Universal Receiver", and the device ID 256f:c652 is just that, the receiver dongle. It's still used as a spacemouse because spacenavd detects 6 axes and buttons, but it doesn't know *which* device it is specifically to apply the correct button mapping, and you get those freaky button numbers instead. You can see that it "guesses" it's a spacemouse wireless, but it doesn't know it's the "pro" version: "using device: 3Dconnexion SpaceMouse Wireless (guess) (/dev/input/event12)".

One way to side-step this issue is to use the device wired. Then spacenavd will know exactly which device it is, and apply the correct button mapping. That might be inconvenient, but will work without further changes.

To make it work correctly wirelessly and have the buttons in the correct order, there are two options for me. One is to add a heuristic. If there are more than two buttons, guess spacemouse wireless pro, instead of spacemouse wireless. The other is to add an option in the config file for the user to force the device to be treated as any of the known devices.

I'll start with the guess heuristic, and we'll see in due time if that causes mis-detection of some other device...

**Comment by Takrel** [comment]
I would take the second options.
Add a dropdown menu who the user can choice which model to use.
This would be the option i made.

On the other hand i would make the option that is easier to made if it works.
Sadly i have no clue of programming. So i think you know it much better than me.

Thank you!

**Comment by jtsiomb** [comment]
Try the latest git revision of spacenavd, and let me know if it fixes your issue.

> Add a dropdown menu who the user can choice which model to use.

Yes, spnavcfg has UI elements for each config option, so when I talked about adding a config option to force a specific device, on the UI it would have to be something like a corresponding dropdown menu. I might add that in the future, it's good to have a backup plan if the device is misdetected, but it's a much larger change that needs support across all three projects (spacenavd, libspnav (on the protocol level), and spnavcfg), so I'll leave that for another time.

**Comment by Takrel** [comment]
I'm sorry. I have no idea how i have to use the latest git revision you mentioned.
Now i'm a month on Linux and not very experienced. Many try and error for me.

Can you guide me to a tutorial or explain it for me please?

**Comment by jtsiomb** [comment]
something like:
    cd /tmp
    git clone https://github.com/FreeSpacenav/spacenavd
    cd spacenavd
    ./configure
    make
    sudo make install

You will need to install build tools (compiler, make, development libraries), and the git version control system. You can take the process one step at a time, and when it pops up an error it means you're missing something. Try to figure out what it is and install it.

If you don't feel up to it, it doesn't matter, just use the device wired, and I'll consider the bug fixed unless you or someone else reports otherwise in the future.

**Comment by Takrel** [comment]
It runs fine until i type "sudo make install"
Then i get an error message: cp: reguläre Datei '/usr/local/bin/spacenavd' kann nicht angelegt werden: Das Programm kann nicht ausgeführt oder verändert werden (busy)
make: *** [Makefile:47: install] Fehler 1

**Comment by jtsiomb** [comment]
Even though I don't speak your language, and I'm not sure why you thought I should understand that... I did :) You need to stop spacenavd first, otherwise the install rule can't overwrite the binary with the new one.

**Comment by Takrel** [comment]
I've managed it now to install.
Had to stop the agent for this.

Now its guessing my device right. Thank you!
All working now :)
