### ISSUE TITLE
full /etc/spnavrc file is stripped of options after spnavcfg is run

### ISSUE THREAD

**Issue by dlarue** [FreeSpacenav/spnavcfg#8]
I've setup my /etc/spnavrc file as in doc/example_spnavrc with log file, button remapping etc but after running spnavcfg that all gets stripped down to just a few lines and many settings are removed.

Both built from source today.
spacenavd v0.7.1 on Ubuntu 18.04.3
spnavcfg v0.3

**Comment by jtsiomb** [comment]
Thanks for reporting the issue. The problem is that there's some code duplication regarding configuration file parsing and saving between spacenavd and spnavcfg. They both have a copy of `cfgfile.c` which handles this sort of thing, and the files have fallen out of sync, as the GUI confguration program has not been updated for some time. As a stopgap, you may copy the `cfgfile.h` and `cfgfile.c` from spacenavd over to spnavcfg and recompile. This should "fix" the problem of dropping unknown config options from the file.

The long term "correct" solution would be for the GUI to not touch the configuration file at all, and instead communicate the changes to spacenavd, and let the daemon handle configuration loading/saving changes on its own.

**Comment by jtsiomb** [comment]
I just updated the cfgfile handling code in spnavcfg. This should solve the issue in the short term. Feel free to reoppen if this happens again.
